### ISSUE TITLE
Horizontal inside Vertical layout manager

### ISSUE THREAD

**Issue by aimanbaharum** [sockeqwe/AdapterDelegates#10]
Hey, nice approach on delegating adapters.

However I have a few issues regarding this design. Is it possible to have two different RecyclerViews in an adapter? How do I go about doing this with the same data set passed into this adapter?

For the same data set, what I mean is according to your sample, you're implementing every related models to an interface class. How do I split this data set to delegate it to different adapter types?

Thanks!

**Comment by sockeqwe** [comment]
Hi,

> However I have a few issues regarding this design. Is it possible to have two different RecyclerViews in an adapter? How do I go about doing this with the same data set passed into this adapter?

I can't see how this is exactly related  to this library. Do it as you would do it without this library. This library offers just to delegate the "work"  of creating and binding a view holder to a so called `AdapterDelegate`. This ensures that you have composable adapters with composable ViewTypes (ViewHolders). So I guess you are asking: How do I add a Horizontal RecyclerView in a vertial RecyclerView? The same way as without this library: You would have to make a ViewHolder with a horizontal RecyclerView in the layout you are using for this ViewHolder.

> For the same data set, what I mean is according to your sample, you're implementing every related models to an interface class. How do I split this data set to delegate it to different adapter types?

I don't understand what you mean? I guess you mean that in my examples there are classes like `Cat extends Animal`, `Dog extends Animal` and then the adapter dataset is `List<Animal>` and then is do `list.get(postion) instanceof Cat` to determine that this should be delegated to `CatAdapterDelegate`.

So far so good. But what is your question exactly?
