### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by taptappub** [sockeqwe/AdapterDelegates#108]
Hi. Could you help me make an infinite loop in recyclerview with AdapterDelegate? Is it possible?

**Comment by sockeqwe** [comment]
Hey, 
That is hot in particular related to AdapterDelegates but the question is how do you do that in general with RecyclerView and Adapters. Then answer is you need 

1. Specifiy that your Adapter contains an "infinite amount" of items. You can do that by overriding `Adapter.getItemCount()` to `return Integer.MAX_VALUE`.
2. Then in `onBindViewHolder()` you need to map the  position to the desired value. I think `position % realList.size` is what you typically do.

I hope that helps and gives you inspiration.
