### ISSUE TITLE
Setting onClick listeners for each card?

### ISSUE THREAD

**Issue by CCorrado** [sockeqwe/AdapterDelegates#15]
Hey, 

This is more of an improvement. Setting an onClick seems to be a challenge using this method -- Creating the type<T>delegate which extends the adapter delegate for each type<T> and then finding the position which the user has clicked for type<T> in the list -- complex for multiple items in the list, i know....but a necessity for a recycler view that does anything more than just display a list of things with some data.

**Comment by CCorrado** [comment]
IN fact, I see on your site in the comments that you've already created an approach to setting click listeners. Awesome. I was thinking the same thing, but wasn't sure if there was a better way.  http://hannesdorfmann.com/android/adapter-delegates

**Comment by JakeWoki** [comment]
@CCorrado @sockeqwe 
I don't find how to do

**Comment by sockeqwe** [comment]
Pass a listener as constructor parameter of your Delegate ...

Jake Woki <notifications@github.com> schrieb am Mo., 22. Mai 2017, 05:21:

**Comment by JakeWoki** [comment]
add a Adapter param on onBindViewHolder,It may be better.

**Comment by sockeqwe** [comment]
Why?
Also what about longClickListener etc. That will escalate quickly ...

Jake Woki <notifications@github.com> schrieb am Mo., 22. Mai 2017, 09:22:
