### ISSUE TITLE
setFallbackDelegate

### ISSUE THREAD

**Issue by IvanLopezCarreira** [sockeqwe/AdapterDelegates#23]
Hi, first of all, ty for the library. I seen that setFallbackDelegate was removed in 2.0.1 version. What is the motivation? Any workarount to avoid exception if any delegate can control viewtype?

Ty and sorry about my english

**Comment by sockeqwe** [comment]
It hasn't removed:
https://github.com/sockeqwe/AdapterDelegates/blob/master/library/src/main/java/com/hannesdorfmann/adapterdelegates2/AdapterDelegatesManager.java#L283

Maybe you mean something different?

**Comment by IvanLopezCarreira** [comment]
Sorry sockeqwe, my fault. I had bad import.
Delete issue if you want.

Ty

**Comment by sockeqwe** [comment]
No problem,
thanks for your feedback!
