### ISSUE TITLE
Loading more view

### ISSUE THREAD

**Issue by krialix** [sockeqwe/AdapterDelegates#26]
Thank you for the great library. Can you provide an example about how to add and remove loading more view?

**Comment by sockeqwe** [comment]
Typically, you would have an item in your adapter's dataset source representing that you are loading more. So when you start loading more, add such a item at the latest position your adapters data set, then call `notifyDatasetChanged()` and when you are done with loading more remove the item from your dataset.

**Comment by kalyaganov** [comment]
Or you can have the loading item all the time and remove it when you determine that there is impossible to load new items.
