### ISSUE TITLE
Getting Position When Extend it From AbsListItemAdapterDelegate

### ISSUE THREAD

**Issue by eminuluyol** [sockeqwe/AdapterDelegates#31]
Hi,

I was extending my Delegates from AbsListItemAdapterDelegate to reduce amount of boilerplate codes, but when I need to delete item from the list I need the exact position. In overrided OnBindView method you don't provide the position, is there any way to get it and delete the item properly ?

**Comment by sockeqwe** [comment]
You can use ViewHolder.getAdapterPosition()

Mehmet Emin Uluyol <notifications@github.com> schrieb am Di., 24. Jan. 2017
um 10:05 Uhr:

**Comment by eminuluyol** [comment]
It works like a charm. Thank you for this great library!!

**Comment by sockeqwe** [comment]
You are welcome!
I'm happy that this works for you.
