### ISSUE TITLE
Diffing

### ISSUE THREAD

**Issue by PaulWoitaschek** [sockeqwe/AdapterDelegates#35]
I have a question about the adapter delegates.

How can I perform diffing on the data? Let's say I have a Type A that is always on top of the view and a List of Type B that follows.
Now I want to remove Type A. How do I perform the diffing so that the adapter only calls 'notifyItemChanged' on the first position? Or when I reordered the List?
Normally I use DiffUtil but I'm not sure how to apply that here.

**Comment by sockeqwe** [comment]
Works the same way as implementing this directly in `RecyclerView.Adapter`

So simply use DiffUtils and apply the diff result to the adapter.
