### ISSUE TITLE
Add sources to release

### ISSUE THREAD

**Issue by PaulWoitaschek** [sockeqwe/AdapterDelegates#36]
It would be great if the releases contain the source. 
Right now it's difficult to use because there is no JavaDoc, and all the params are random (`  protected abstract void onBindViewHolder(@NonNull T var1, int var2, @NonNull ViewHolder var3, @NonNull List<Object> var4);`

**Comment by sockeqwe** [comment]
Hm, there are sources for both stable release and snapshot:

https://oss.sonatype.org/#nexus-search;quick~adapterdelegates3


https://oss.sonatype.org/content/repositories/snapshots/com/hannesdorfmann/adapterdelegates3/3.0.2-SNAPSHOT/

If I remember correctly it is not possible to publish artifacts to oss.sonatype (and mavencentral in general if I remember correctly) without source code.

That is one of the reasons why for example play services is not available on maven central.

**Comment by PaulWoitaschek** [comment]
![screen](https://cloud.githubusercontent.com/assets/743462/25339055/b1c0e3dc-2901-11e7-84e5-da62fc64a9a2.png)

They are not present for me

**Comment by sockeqwe** [comment]
Hm, strange. I see the sources incl. javadoc.

(running android studion 2.3.1 build #AI-162.3871768, built on April 1, 2017 )

<img width="1280" alt="adapterdelegatessource" src="https://cloud.githubusercontent.com/assets/583598/25339628/9eaa3e22-2903-11e7-8b80-a413a4586475.png">


Seems like an Android Studio issue?

you can try to refresh dependencies manually with

```
gradle build --refresh-dependencies
```

**Comment by PaulWoitaschek** [comment]
Something is wrong with my AS, it affects other libraries too. Thanks!

**Comment by sockeqwe** [comment]
I see that too on my macbook with Android Studio 2.3.1. Not with this
library but with other libraries. Thanks for coming back.

Paul Woitaschek <notifications@github.com> schrieb am Fr., 5. Mai 2017,
09:53:
