### ISSUE TITLE
Adding new feature for Expanding Group

### ISSUE THREAD

**Issue by goransipic** [sockeqwe/AdapterDelegates#39]
Hi,
Do you have interest for adding Feature for Expanding View Group. I can make implementation what your opinion about that ?

**Comment by sockeqwe** [comment]
Not sure if this should be part of this library, let's discuss it. What
exactly do you mean with expanding view groups?

Goran Šipić <notifications@github.com> schrieb am Mo., 5. Juni 2017, 11:08:

**Comment by goransipic** [comment]
Sorry let me Explain better, with expanding view group a mean making list that can expand/collapse, what your way on handling Expandable of recyclerView. What your advance of using AdapterDelegate with recyclerview that can expand/collapse.
[](http://bignerdranch.github.io/expandable-recycler-view/)

**Comment by sockeqwe** [comment]
ah, i see ... 
you mean some kind of "Grouped" items? example
A list like:
```
A
B
C
```

by clicking on  A "children" of this "category" become visible:
```
A
  - A1
  - A2
  - A3
B
C
```

Usually I do this as part of my business logic. So when a user clicks on "A" my adapter is not displaying "A1", "A2", "A3" immediately. Actually the adapter has no knowledge of "A1", "A2", "A3" nor that "A" can expand. So the adapter's dataset doesn't contain "A1", "A2", "A3". 

If user clicks on "A", i pass this "event" down to my business logic and return a new dataset with "A1", "A2", "A3" in the dataset and then I pass this new list as dataset to the adapter and call notifyDatasetChanged() (or with animations with DiffUtils). So the dataset is immutable and testable (part of business logic).

How would you suggest to implement this?

**Comment by goransipic** [comment]
Your way on handling "Grouped" items it's simple and Easy.
