### ISSUE TITLE
Adapter Methods

### ISSUE THREAD

**Issue by pixelbendr** [sockeqwe/AdapterDelegates#4]
Hello,

I have some adapter methods in which I almost repeat for all adapters. Where should it be so I don't have to repeat but also can enable or disable which feature I want in individual adapters.

Or I should just create an interface, extend the recycler view method. And use super and override to disable and enable functionality?

   public void add(Object item) {
        list.add(item);
    }

    public void addItem(Object item) {
        add(item);
        notifyDataSetChanged();
    }

    public void removeItem(int position) {
        list.remove(position);
        notifyItemRemoved(position);
    }

    public void clearItems() {
        list.clear();
    }

**Comment by sockeqwe** [comment]
I'm not sure if I inderstood your question correctly,  but your common code you want to share is `addItem()`, `removeItem()` and `clearlItems()` right? So in that case i think it's completely fine to.put that code in a base adapter class and extend from it as needed.

**Comment by pixelbendr** [comment]
Ok thanks. I will do just that. Am a little knew to Android. :)

**Comment by sockeqwe** [comment]
you are welcome!

Evans Domina Attafuah <notifications@github.com> schrieb am Do., 13. Aug.
2015 23:44:
