### ISSUE TITLE
Testing onCreateView/onBindView with Robolectric

### ISSUE THREAD

**Issue by noloman** [sockeqwe/AdapterDelegates#44]
Hey!
First of all, thank you very much for the library. It is a very smart and useful thing to work with, and it just works great!

Currently I need to test a RecyclerView whose adapter uses AdapterDelegates for setting up different types of adapters for several view types, and I would do this by using Robolectric.

The way I would test is the following, as if I was using any ordinary RecyclerView.Adapter:

Let's say I have an adapter:

```java 
myCoolAdapter = new CoolAdapter(this,
                allVehicles,
                getSupportFragmentManager(),
                accountListener,
                confirmedListener,
                connectedListener,
                unconnectedListener);
```

And this adapter is defined as follows:

```java
public class CoolAdapter extends AbsDelegationAdapter<List<Pair<Boolean, List<?>>>> {
    private final HeaderDelegate headerDelegate;

    public CoolAdapter (Context context, List<Pair<Boolean, List<?>>> connectedVehicles,
                                        FragmentManager fragmentManager,
                                        HeaderDelegate.AccountListener accountListener,
                                        ConfirmedDelegate.ConfirmedListener confirmedVehicleItemListener,
                                        ConnectedDelegate.ConnectedListener connectedListener,
                                        UnconnectedDelegate.UnconnectedListener unconnectedListener) {
        // We make if a field, so we can have access to the current position of the ViewPager
        headerDelegate = new HeaderDelegate(accountChangedListener, fragmentManager);
        delegatesManager.addDelegate(headerDelegate);
        delegatesManager.addDelegate(new GroupTitleDelegate());
        delegatesManager.addDelegate(new ConnectedDelegate(context, connectedListener));
        delegatesManager.addDelegate(new ConfirmedDelegate(context, confirmedListener));
        delegatesManager.addDelegate(new UnconnectedDelegate(unconnectedListener));
        delegatesManager.addDelegate(new GroupTitleDelegate());
        setItems(connectedVehicles);
    }
...
}
```

Now let's say that I want to test that my CoolAdapter in this way:

```java
ConnectedDelegate.ConnectedViewHolder connectedViewHolder =
                (ConnectedDelegate.ConnectedViewHolder) myCoolAdapter.onCreateViewHolder(myRecyclerView, myCoolAdapter.getItemViewType(6));
        myCoolAdapter.onBindViewHolder(connectedVehicleViewHolder, 6);
```

Knowing that the item at position 6 for this viewType should be of type ConnectedViewHolder works perfectly. The problem comes with the following code:

`myCoolAdapter.onBindViewHolder(connectedViewHolder, 6);`

Even tho I see that `connectedViewHolder` is correctly retrieved from the delegates, the fields `mPosition`, `mItemId` , `mItemViewType` are all `-1`, and `mOwnerRecycerView` are `null`.
Is there any way to overcome this? How come this happens?

Thanks a lot for the help and advance.

**Comment by sockeqwe** [comment]
Hey, 
these properties are set and managed by RecyclerView.
So you have to run that on a RecyclerView to ensure that these properties are set properly. Not sure if RecyclverView works with Robolectric (never tried).

However, what are you actually trying to test? What goal do want to achieve with that test?

**Comment by noloman** [comment]
Thanks for the fast reply!
We are UI testing the rows, basically we get the ViewHolderand check that it has properly bound the data in the row of the RecyclerView

**Comment by sockeqwe** [comment]
I'm not sure if that is worth the effort. 
With that said: if you need  mPosition, mItemId , mItemViewType, and mOwnerRecycerView (why do you need that?)
I would try to run a RecyclerView with an adapter containing the single data item for that AdapterDelegate and then do your verifications. As said, never tried to do that with Robolectric.

**Comment by sockeqwe** [comment]
Inactive
