### ISSUE TITLE
Conflict with android support v4

### ISSUE THREAD

**Issue by cuongmanhvo162** [sockeqwe/AdapterDelegates#45]
I got the error when add AdapterDelegates into my Gradle

Error:Execution failed for task ':comico_client:transformClassesWithJarMergingForAlphaRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/view/PagerTitleStripIcs$SingleLineAllCapsTransform.class

**Comment by sockeqwe** [comment]
This is not related to this library. You can also exclude specific versions of support librarary like described here: https://stackoverflow.com/a/39332108/997851
