### ISSUE TITLE
onBindViewHolder

### ISSUE THREAD

**Issue by Demin92** [sockeqwe/AdapterDelegates#48]
Hi,
Why methods `onBindViewHolder` and `isForViewType` have all items as parameters? We need just current item, not all of them
That is critical because I tried to use your library with Paging library from Architecture Components where i can not get items from adapter

**Comment by sockeqwe** [comment]
`items` because it is not bound to a `List` only. So theoretically, you could also iterate over a `Set`, `Map`, `Array` or `Tree` ...

What exactly is the problem with Paging library? Can you give me an example?
