### ISSUE TITLE
Funny Animation In Recyclerview

### ISSUE THREAD

**Issue by pixelbendr** [sockeqwe/AdapterDelegates#5]
The implementation doesn't work well with recycler view set item animator. Am using a library that does the animation for me. I think it has something to do with notifyDataSetChanged. I might be wrong. 

animator library
compile 'jp.wasabeef:recyclerview-animators:1.2.0@aar'

**Comment by sockeqwe** [comment]
From the readme file of https://github.com/wasabeef/recyclerview-animators I can't see why AdapterDelegates should cause problems. AdapterDelegates doesn't call `notifyDatasetChanged()`.

**Comment by pixelbendr** [comment]
Yes. Noticed that. Will just do some more testing. Thanks
