### ISSUE TITLE
Incompatible with AndroidX

### ISSUE THREAD

**Issue by adolgiy** [sockeqwe/AdapterDelegates#53]

**Comment by sockeqwe** [comment]
yeah, unfortunately this is not an easy fix.
The plan at the moment is to publish `AdapterDelegates4` which is using only `androidx` once `androidx 1.0` has been released (currently beta 1) but I'm open to discuss this. Any thoughts?

**Comment by adolgiy** [comment]
Yep, as I found today, migration can be done by only renaming packages. So it looks like not so hard.

But I'm totally agree to have update when stable release will be available.

**Comment by Bodo1981** [comment]
how about an extra module "adapterdelegates-androidx" which contains the androidx compatible version and keep the "normal" module for all not androidx users? i can create a pull request, because i have already done i migration for my self

**Comment by sockeqwe** [comment]
Yeah, I thought about generating this with a shell script on the fly while
publishing artifact (its basically just replace imports). Advantage is we
only have to maintain one single code basis and not apply bugfixes and so
on 2 times

Bodo1981 <notifications@github.com> schrieb am Mo., 16. Juli 2018, 20:33:

**Comment by technoir42** [comment]
I don't see why all the extra work of maintaining/publishing non-AndroidX module is even needed. People who can't switch yet can use 3.0.1 which is feature complete and stable. And eventually everybody will switch to AndroidX and the latest AdapterDelegates.

**Comment by sockeqwe** [comment]
I think you are right. I just wanted to avoid duplicate maintenance cost for new features api changes but they should be very minimal so that it's not a big deal to do that manually even on a 3.x version (android x would be 4.x).

**Comment by Vivecstel** [comment]
any news on androidx adapter delegates ?

**Comment by sockeqwe** [comment]
Working on it tonight.

**Comment by xsveda** [comment]
> Will they keep publishing just androidx or have some time period where both artifacts will be published

Android support library 28.0.0 has equal functionality as AndroidX 1.0.0. and is the last support lib released. From now on only AndroidX libraries will be updated so there is (almost) no period when these two library sets will co-exists side-by-side.

**Comment by sockeqwe** [comment]
Short update: I have some trouble uploading signed artifacts because I have a new macbook and wasn't fully able yet to properly install my signing key ...

**Comment by Vivecstel** [comment]
@sockeqwe Do we have an update for the release date for the new version ?

**Comment by sockeqwe** [comment]
see #61 

https://github.com/sockeqwe/AdapterDelegates/issues/61#issuecomment-425060078

**Comment by dannyroa** [comment]
Hey peeps. Hannes replied just 2 days ago. He needs to work like we do. Let's cut him some slack.

**Comment by sockeqwe** [comment]
Thanks @dannyroa

In case someone has experience with gpg, I could need some help:

https://stackoverflow.com/questions/52598995/why-is-gradle-is-not-signing-my-artifacts

**Comment by sockeqwe** [comment]
btw. in the meantime you can use Jetifier. I tried it, it works fine with this library:

https://stackoverflow.com/questions/51680671/what-is-jetifier

**Comment by sockeqwe** [comment]
Update: I solved the signing problems. I just have released 3.1.0 with Async List Differ support. 

I will release AdapterDelegates 4.0 which is build on AndroidX soon (tomorrow).

**Comment by sockeqwe** [comment]
I just have released 4.0 which uses RecyclerView from AndroidX. 
I have added a migration section to README
