### ISSUE TITLE
Need position as parameter inside AbsListItemAdapterDelegate.onBindViewHolder

### ISSUE THREAD

**Issue by kelvinc1024** [sockeqwe/AdapterDelegates#55]
Need position as parameter inside AbsListItemAdapterDelegate.onBindViewHolder
for example : 
- Might be useful for position tracking, in that case item only is not sufficient
RecyclerView.onBindViewHolder also contains position
```
public abstract void onBindViewHolder(@NonNull VH holder, int position);
```

**Comment by kelvinc1024** [comment]
PR provided
https://github.com/sockeqwe/AdapterDelegates/pull/56

**Comment by kelvinc1024** [comment]
PR provided here : https://github.com/sockeqwe/AdapterDelegates/pull/57

**Comment by sockeqwe** [comment]
Hey Kevin, 
thanks for your work and pull request.

However, you can get the viewholders position in the adapter directly via `viewHolder.getAdapterPosition()`. See https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ViewHolder.html#getAdapterPosition().

**Comment by kelvinc1024** [comment]
Just realize it. Many thanks!
