### ISSUE TITLE
Paging library

### ISSUE THREAD

**Issue by tallnato** [sockeqwe/AdapterDelegates#61]
Great work with this lib 👏 

Any changes this it will provide compatibility with Android Paging Library from the architecture components?

**Comment by sockeqwe** [comment]
Hi there 👋
I have to look into the details, but I think it should be straigh forward.
Do you wanna contribute / help implement this?

Renato Almeida <notifications@github.com> schrieb am Sa., 8. Sep. 2018,
23:48:

**Comment by makarenkoanton** [comment]
Hi, thanks for your lib. 
I use your 3.0.2 snapshot, and now not working boundary callback for PageList. 
Do you have some roadmap about paging library and your lib?)

**Comment by sockeqwe** [comment]
The plan is the following:

1. Release 3.1.0 which contains async list differ so that we have the equivalent to `ListAdapter` from support library (that uses `DiffUtil` and `AsyncListDiffer` under the hood). This is already in latest master. However, I wasn't able to upload this to maven central yet because of some signing pgp issues on my new macbook.

2. Once 1. is solved I will migrate library to jetpack and release it as `AdapterDelegates 4.0`. This should be very straight forward.

3. Add support for `PageList`. This as well should not be a big deal, just a few hours to sit down (or in case someone wants to contribute, PR are welcome).

**Comment by sockeqwe** [comment]
Working on that as a next step. Mabye somewhen next week.

**Comment by sockeqwe** [comment]
Latest `4.0.1-SNAPSHOT` contains a [PagedListDelegationAdapter](https://github.com/sockeqwe/AdapterDelegates/tree/master/paging). It should work with `PagedList` as shown in the [sample application](https://github.com/sockeqwe/AdapterDelegates/blob/master/app/src/main/java/com/hannesdorfmann/adapterdelegates4/sample/pagination/PaginationActivity.java).
Unfortunately, I wasn't yet able to implement the datasource for the sample application properly (PR are very welcome) but it would be great if you could give it a try and let me know if it works in your project.

**Comment by tallnato** [comment]
@sockeqwe I was testing that new release and I think you are not deploying the paging library to sonatype 🤔 
Probably missing some configs in the [deploy_snapshot.sh], no? (https://github.com/sockeqwe/AdapterDelegates/blob/master/deploy_snapshot.sh)

I'm tested with Jitpack and from my tests it seems to be ok 👌

**Comment by sockeqwe** [comment]
You are right, there was something missing.

Snapshot is available now.

**Comment by akhbulatov** [comment]
@sockeqwe I've added `4.0.1-SNAPSHOT` version and not found `PagedListDelegationAdapter` in the lib

**Comment by sockeqwe** [comment]
It's a second artifact (I messed it up, but for final `4.0.1` version I will clean it up and give it a proper artifact name).


Please try

```
allprojects {
  repositories {
    ...

    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```


```
implementation  'com.hannesdorfmann:paging:4.0.1-SNAPSHOT'
```

**Comment by sockeqwe** [comment]
@akhbulatov did it work for you?

**Comment by akhbulatov** [comment]
@sockeqwe yes, it works

**Comment by sockeqwe** [comment]
Latest release: implementation  'com.hannesdorfmann:adapterdelegates4-pagination:4.1.0'
