### ISSUE TITLE
 AsyncListDiffer IndexOutOfBoundsException: Index: 1, Size: 21

### ISSUE THREAD

**Issue by har5hit** [sockeqwe/AdapterDelegates#64]
Support Lib: 27.1.1

Library used: Hannesdorfmann Adapterdelegates3 (https://github.com/sockeqwe/AdapterDelegates),
AsyncListDifferDelegationAdapter

Version: com.hannesdorfmann:adapterdelegates3:3.1.0

Setup:

A FragmentStatePagerAdapter with 3 Fragments containing a RecyclerView with an instance of AsyncListDifferDelegationAdapter.

List of data is emitted to listing fragment using Viewmodel and Livedata,

The Livedata is observed using observeForever(due to business rule) and subscribed in OnViewCreated and unsubscribed on onDestroyView() in the listing fragment.

Issue:

Randomly during updating recyclerview list, when new list is submitted to the AsyncListDiffer, 
IndexOutOfBoundsException is thrrown inside android.support.v7.recyclerview.extensions.AsyncListDiffer without stacktrace of the fragment in which it was used, Also the exception thrown is incorrect and crashing the app.

Device:

Samsung Galaxy J7 Prime(SM-G610F)
OS: Android 8.1.0
Samsung experience version: 9.5

Please help with any workarounds or any idea how to handle the exception or fix it.

StackTrace:
03-20 16:10:16.016 26291 26518 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 21
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at java.util.ArrayList.get(ArrayList.java:437)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at android.support.v7.recyclerview.extensions.AsyncListDiffer$1$1.areItemsTheSame(AsyncListDiffer.java:239)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at android.support.v7.util.DiffUtil.diffPartial(DiffUtil.java:224)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at android.support.v7.util.DiffUtil.calculateDiff(DiffUtil.java:136)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at android.support.v7.util.DiffUtil.calculateDiff(DiffUtil.java:97)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at android.support.v7.recyclerview.extensions.AsyncListDiffer$1.run(AsyncListDiffer.java:225)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-20 16:10:16.016 26291 26518 E AndroidRuntime: at java.lang.Thread.run(Thread.java:764)

56.318 20749 20948 E AndroidRuntime: Process: com.shaadi.android, PID: 20749
03-20 15:31:56.318 20749 20948 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 4, Size: 21
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at java.util.ArrayList.get(ArrayList.java:437)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at android.support.v7.recyclerview.extensions.AsyncListDiffer$1$1.areItemsTheSame(AsyncListDiffer.java:239)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at android.support.v7.util.DiffUtil.diffPartial(DiffUtil.java:259)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at android.support.v7.util.DiffUtil.calculateDiff(DiffUtil.java:136)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at android.support.v7.util.DiffUtil.calculateDiff(DiffUtil.java:97)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at android.support.v7.recyclerview.extensions.AsyncListDiffer$1.run(AsyncListDiffer.java:225)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-20 15:31:56.318 20749 20948 E AndroidRuntime: at java.lang.Thread.run(Thread.java:764)
03-20 15:31:56.439 18411 18445 E PBSessionCacheImpl: sessionId[80973987391565932] not persisted.

**Comment by sockeqwe** [comment]
Hi there,
Thanks for reporting.

Just by looking at the stacktrace, I don't think this problem is coming from the Adapter delegates library.

Do you have some more insights why you think it is related to this library? Can you reproduce this bug? Is the code open source somewhere sonthatbI can take a look at it? 
To me it seems like something inside your DiffUtil.callback is wrong or somethung inside RecyclerView library itself. In both cases I can't help you unfortunately.

**Comment by har5hit** [comment]
Hello, 
Thanx for the reply.

The project its happening in is closed source, otherwise would have shared it with you. But will try to create a demo project if i'll be able to reproduce the same issue on it.

I thought this maybe a random issue that maybe happening with some people who can suggest a solution or you might know if there's something in the library that may cause this if i implemented it improperly.

Closing this issue till i'll be able to reproduce it in a demo project, as i understand it will be hard without source code.

**Comment by sockeqwe** [comment]
thanks @har5hit
