### ISSUE TITLE
Paging library not working with PagedListDelegationAdapter

### ISSUE THREAD

**Issue by roshanthejoker** [sockeqwe/AdapterDelegates#65]
Hi,I have implemented paging library and I am using the PagedListDelegationAdapter. But the datasource's loadAfter method is not being called and I think the reason is the delegate adapter is not calling getItem() function which I guess kicks in the loadAfter function in datasource. Any help is appreciated.

**Comment by sockeqwe** [comment]
Hi,
thanks for reporting. I think you are right. I have updated the snapshot (and changed artifact id): Could you please try

`implementation com.hannesdorfmann:adapterdelegates4-pagination:4.0.1-SNAPSHOT`

**Comment by roshanthejoker** [comment]
I am using the v3 version of the lib. But I'll try making a sample app and verify. I possible can you backport this fix to v3.

**Comment by sockeqwe** [comment]
v3 doesn't officially support pagination but yeah, maybe I can backport it anyway ...

I have just added the `getItem()` call in `bindViewHolder()`:
https://github.com/sockeqwe/AdapterDelegates/blob/master/paging/src/main/java/com/hannesdorfmann/adapterdelegates4/paging/PagedListDelegationAdapter.java#L67



Basically you could copy the whole file from v4 and replace androidx with support library imports.
https://github.com/sockeqwe/AdapterDelegates/blob/master/paging/src/main/java/com/hannesdorfmann/adapterdelegates4/paging/PagedListDelegationAdapter.java

**Comment by roshanthejoker** [comment]
I had implemented the same by copying the file. Thanks for the library. It greatly simplifies handling different viewtypes. Closing the issue.
