### ISSUE TITLE
DIFF ADAPTER Error

### ISSUE THREAD

**Issue by lydlovexyz** [sockeqwe/AdapterDelegates#66]
<img width="893" alt="微信截图_20190428095832" src="https://user-images.githubusercontent.com/19246347/56857143-73324600-699c-11e9-8236-a7a614bcd47e.png">

**Comment by sockeqwe** [comment]
Hi,
I think this is not an problem of this library.


Did you set the dataset somewhere manually? I would recommend to you to
google for that error message. Again, I dont think it is an error of this
library but rather somewhere in your code.

lydlovexyz <notifications@github.com> schrieb am So., 28. Apr. 2019, 04:00:

**Comment by lydlovexyz** [comment]
not my code,error in your demo project!

**Comment by sockeqwe** [comment]
Ah thanks, than my demo code may have a bug, but I'm still vonfident that
it is not a bug of the library as all the library does is calling
components from RecyclerView library. So either it is a bug in RecyclerView
library or in the demo code. I will check it out later. Any idea how to
reproduce this issue?

lydlovexyz <notifications@github.com> schrieb am So., 28. Apr. 2019, 11:03:
