### ISSUE TITLE
Lint Rule that checks that no top level property uses kotlin DSL

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/AdapterDelegates#69]
the new kotlin DSL is nice but could lead to memory leaks if you use a top level `val` in a kotlin file as such a top level `val` will internally result in a static field that will be kept forever. Thus, the context of the adapter delegate might be kept forever around (leaking activity).

**Comment by PaulWoitaschek** [comment]
Is it really like that? Can you explain where the context is being leaked?

The [body](https://github.com/sockeqwe/AdapterDelegates/blob/master/kotlin-dsl/src/main/java/com/hannesdorfmann/adapterdelegates4/dsl/ListAdapterDelegateDsl.kt#L33-52) of the top level function is stateless and so is the [DslListAdapterDelegate](https://github.com/sockeqwe/AdapterDelegates/blob/master/kotlin-dsl/src/main/java/com/hannesdorfmann/adapterdelegates4/dsl/ListAdapterDelegateDsl.kt#L58) as well as [AbsListItemAdapterDelegate](https://github.com/sockeqwe/AdapterDelegates/blob/master/library/src/main/java/com/hannesdorfmann/adapterdelegates4/AbsListItemAdapterDelegate.java) and [AdapterDelegate](https://github.com/sockeqwe/AdapterDelegates/blob/master/library/src/main/java/com/hannesdorfmann/adapterdelegates4/AdapterDelegate.java).

You write
> Never ever use a top level val to hold a reference as top level val are static and will hold a reference to the adapter 

Why do delegates hold references to the adapter? IIRC the adapter holds references to the delegates, but that shouldn't leak anything.

**Comment by sockeqwe** [comment]
you are right thanks for pointing it out.

in my first draft ´layoutInflater´ was not a pure function but was a private val of type LayoutInflater and leaked the underlying context.

https://github.com/sockeqwe/AdapterDelegates/blob/93aefa0f769c46e332bee4f7a769ed76ac4bd0cb/kotlin-dsl/src/main/java/com/hannesdorfmann/adapterdelegates4/dsl/ListAdapterDelegateDsl.kt#L61

 Thanks again for all your contribution and help
