### ISSUE TITLE
mention androidExtensions experimental=true in readme for LayoutContainer

### ISSUE THREAD

**Issue by grieser-careoline** [sockeqwe/AdapterDelegates#77]
Hi Hannes,

please include an note in the readme for kotlin-dsl-layoutcontainer to add 
```
androidExtensions {
    experimental = true
}
```
in build.gradle (app).

I spent 3 days figuring this out, why i get null-exceptions at runtime in the ListDelegationAdapter, while studio doesn't complain.

Thank you.

**Comment by sockeqwe** [comment]
Oh I'm sorry 😳

Do you want to send a pull request?

grieser-mcsh <notifications@github.com> schrieb am Di. 10. Sep. 2019 um
07:54:

**Comment by sockeqwe** [comment]
Added.
