### ISSUE TITLE
LayoutContainer.findCachedViewById

### ISSUE THREAD

**Issue by 1PakMan1** [sockeqwe/AdapterDelegates#80]
Why _$_findCachedViewById is not used in bind method

**Comment by sockeqwe** [comment]
Can you elaborate what you exactly mean? What is the issue and what is the
expected behavior?

1PakMan1 <notifications@github.com> schrieb am Mi., 8. Jan. 2020, 19:29:

**Comment by 1PakMan1** [comment]
As soon as you implement the LayoutContainer interface, findViewCache variable and corresponding findCachedViewById & clearFindViewByIdCache methods are generated. Caching mechanism allows to improve performance of a view holder.
But when we decompile adapterDelegateLayoutContainer we can see that  neither of those methods are used in bind method or anywhere else.
Is there any reason why we cannot use findCachedViewById instead findViewById?

**Comment by sockeqwe** [comment]
See #81

**Comment by sockeqwe** [comment]
I have just released 4.3.0 which contains a fix for this. Please give it a try and let me know if that solved the problem.

**Comment by 1PakMan1** [comment]
Thanks a lot for quick fix and this excellent library!
