### ISSUE TITLE
Is this possible to all delegate adapter has pagingadapter

### ISSUE THREAD

**Issue by abalta** [sockeqwe/AdapterDelegates#84]
Hi, I want to build app like Google Play or Netflix style app. Each section has paging ability, like Popular Movies section, Featured Movies section etc. and also each section has horizontal orientation with paging feature.. Is this possible to make build this kind of app with using your AdapterDelegates. Because, I have checked your sample app all section has vertical.

**Comment by sockeqwe** [comment]
Sure, this library is only about adapters. Adapters are independent from
scroll direction. Thus,  it will work for horizontal or even recyclerviews
inside recyclerviews.

Abdullah Balta <notifications@github.com> schrieb am Di., 31. März 2020,
02:20:
