### ISSUE TITLE
Nested Recycler View question

### ISSUE THREAD

**Issue by PaulEHugon** [sockeqwe/AdapterDelegates#85]
Hi there,

My question is regarding a nested Recycler view. Basically I have a PagedList of UserDisplay that is coming from my Mosby MVI Presenter composed with two objects:
```Kotlin
data class HeaderUserManagement(var header:String):UserDisplay
data class ParentUser(var userType:List<UserFirebaseStorage>):UserDisplay
```

I want to display the userType List into a child Recycler view(himself inside a cardview) inside  the parent Recycler view(left picture below)

I then created my adapters delegate as follow:

```Kotlin
fun headerUserManagementAdapterDelegate() =
    adapterDelegateLayoutContainer<HeaderUserManagement, UserDisplay>(R.layout.user_header_item) {

        bind {
            //Log.d("testRecyclerHeader", itemViewType.toString())
            tvHeaderUser.text = item.header
        }
    }

fun parentUserManagementAdapterDelegate(adapterChild: ListDelegationAdapter<List<ChildDisplay>>) =
    adapterDelegateLayoutContainer<ParentUser, UserDisplay>(R.layout.item_user_test) {

        bind {
            //Log.d("testRecyclerParent", itemViewType.toString())
            //Log.d("testRecyclerParent", item.userType.toString())
            val linearLayoutManager = LinearLayoutManager(this.context)
            rvNested.layoutManager = linearLayoutManager   
rvNested.addItemDecoration(DividerItemDecoration(this.context,LinearLayoutManager.VERTICAL))
            adapterChild.items = item.userType
            rvNested.adapter = adapterChild
        }
    }

fun userFirebaseStorageAdapterDelegate(uFSClickedListener:(UserFirebaseStorage)->Unit) =
    adapterDelegateLayoutContainer<UserFirebaseStorage, ChildDisplay>(R.layout.item_user) {

        mcvUserRV.setOnClickListener { uFSClickedListener(item) }

        bind {
            tvUserName.text = item.userFirebase.name
            tvUserCreditCard.text = item.userFirebase.creditCard
            tvUserEmail.text = item.userFirebase.email

        }
    }
```

And then my delegates manager and PagesListDelegationAdapter

```Kotlin
private val delegatesManager = AdapterDelegatesManager<List<UserDisplay>>()
        .addDelegate(headerUserManagementAdapterDelegate())
        .addDelegate( parentUserManagementAdapterDelegate(
            ListDelegationAdapter(
                userFirebaseStorageAdapterDelegate { userFirebaseStorage: UserFirebaseStorage ->
                    uFSClicked(
                        userFirebaseStorage
                    )
                })
        ))

private val adapterPaged = PagedListDelegationAdapter(delegatesManager,callback)
```
recycler view init:

```Kotlin
 rvAdminUserManagement.apply {
            val llm = LinearLayoutManager(this.context)
            layoutManager = llm
            adapter = adapterPaged
            setOnScrollChangeListener { _, _, _, _, _ ->

                mcvToolbarUserManagement.isSelected = this.canScrollVertically(-1)

            }
        }
```
So this is working fine and i have my list in a second Recycler View inside a card view as wanted(left picture below). However I also have a bottomSheet with an edit text inside in this fragment. When I open the bottom sheet and type inside the edit text and collapse the bottom sheet the Child Recycler view changed(right picture below). The last item of the second nested recycler view is now visible on the first nested recycler view... Logcat is completely empty and the Parent and child Recycler views are not redrawn.

![Error recycler view](https://user-images.githubusercontent.com/48159913/78574953-028ddd80-782b-11ea-8ab1-52742e1fdb14.jpg)

My first question would be am I doing everything as it should be done with the library to display nested recycler view? If yes why i have this weird behavior?
Thank you for reading me and hope somebody can be of any help.

**Comment by sockeqwe** [comment]
Hi, I think the problem that you describe is not related to this library. nested recyclerview work just fine. 

To me it looks like you have an issue in your dataset management somehow

**Comment by PaulEHugon** [comment]
Hi,

Thank you so much for your answer.

> if that all looks good from your side we could check if ˋ PagedListDelegationAdapterˋ has a bug but from your description I think this is not the case

Since then I changed from PagedListDelegationAdapter to ListDelegationAdapter and problem was similar. So the problem doesn't lie there I think.I also switch to the view binding DSL but same problem.

> To me it looks like you have an issue in your dataset management somehow.i would recommend to debug your dataset --> adapter calls.
> 
The Dataset comes from the Mosby MVI presenter whit an Intent that is launched once at fragment Start(Observable.just). I Logged the data and it is coming all good as planned from my Interactor to the Presenter. Then i just render the data as follow:
```Kotlin

 private fun renderUserStart(userList: List<UserDisplay>?) {
        adapterList.items = userList
        adapterList.notifyDataSetChanged()
    }
```
So from there all good the data is displayed properly(left picture first post). However as soon as a UI movement occur(like animation motion layout or softKeyboard popping up) it seems the items from the second nested recycler view are recycled into the first nested recycler view(the right picture on the first post).
Then I decided to change my Dataset. I splitted the ParentUser into two different class(Admin User and Normal User both implementing UserDisplay). I then created an adapterDelegate for each and the problem was still coming.
Then I decided to create two different items to display the data and the problem is now gone. The problem is now I have 1 more class than before and 2 more adapterDelegate which is okay for now but what if I have 10 or 20 recyclerView to display...
 
>  also worthwhile to check if you dont accidentally mess up the shared instance of ˋadapterChild: ListDelegationAdapter<List>ˋ as this sounds fragile (dangerous).
> 
You might be right here but I'm not sure I fully understand what you mean and how I would check that.

**Comment by sockeqwe** [comment]
i would recommend to do the following:

use your original adapter setup where you see the issue. but instead of
using the real data, use a hardcoded userList:

 private fun renderUserStart(userList: List<UserDisplay>?) {

        adapterList.items = listOf(item1, item2, ...) // some hardcoded values

        adapterList.notifyDataSetChanged()

    }



if you can observe still the problem with the hardcoded dataset I would
start looking into what I meant with shared instance in my previous
message.I mean why do you pass ˋadapterChild: ListDelegationAdapterˋ as a
function parameter? i think you should create that in

fun parentUserManagementAdapterDelegate(adapterChild: ListDelegationAdapter<
List<ChildDisplay>>) = ...

from my point of view you should instantiate the adapter:
ListDelegationAdapter inside the adapterDelegateLayoutContainer{ ... }
block but outside of the bind block.

PaulEHugon <notifications@github.com> schrieb am Fr. 10. Apr. 2020 um 17:31:

**Comment by PaulEHugon** [comment]
>use your original adapter setup where you see the issue. but instead of
using the real data, use a hardcoded userList>

Same issue there with hardcoded list

>  from my point of view you should instantiate the adapter: ListDelegationAdapter inside the adapterDelegateLayoutContainer{ ... } block but outside of the bind block. 

Bingo this was the solution... Thank you so much for your help. I'm  a newly converted android Developper and I still have a lot to learn. But I'm learning from my mistakes it's good. Do you think it is worst mentioning in the ReadMe that we shouldn't pass the adapter as parameter?

**Comment by sockeqwe** [comment]
Glad that it helped. Btw. you should also move the child RecyclerViews
layoutManager also out of the bind block. Instantiating adapter, setting
adapter and layoutManager should be in the adapterDelegate{ ... } block but
outside of the bind block. Bind is called every time a new cell comes
visible on the screen. It that case you dont want to reinstantiate the
child RecyclerViews layoutManager and adapter. That is a one-time thing
that should be done in the adapterDelegate block but outside of bind block

PaulEHugon <notifications@github.com> schrieb am Fr., 10. Apr. 2020, 18:59:

**Comment by sockeqwe** [comment]
Oh and regarding to adding thinks like that to readme: I think this is
general knowledge about RecyclerViews and not specific to this library. You
would end up with the same issue if you would use plain Adapter and
ViewHolders without this library.

Hannes Dorfmann <hannes.dorfmann@gmail.com> schrieb am Fr., 10. Apr. 2020,
19:58:
