### ISSUE TITLE
adapterDelegateViewBinding doesn't work for ViewDataBinding

### ISSUE THREAD

**Issue by mihaiAdascalitei** [sockeqwe/AdapterDelegates#87]
Hello, 
I tried to implement the adapter delegate using dataBinding but as a result I've got the following issue :
  - I used adapterDelegateViewBinding to create a new adapterDelegate but it uses only ViewBinding, therefore ViewDataBinding is excluded.

**Comment by sockeqwe** [comment]
hi, 
what exactly is not working? 
can you take a look at the demo app here?

**Comment by mihaiAdascalitei** [comment]
Hello,
I've followed the demo and the doc again but it is the same issue .

![image](https://user-images.githubusercontent.com/26079928/81656511-c4926380-943f-11ea-8c58-8d2517d20fbd.png)

The idea is that your method `adapterDelegateViewBinding ` works only with ViewBinding and not with ViewDataBinding .

![image](https://user-images.githubusercontent.com/26079928/81656705-e986d680-943f-11ea-9df3-9f88fd7f4874.png)

![image](https://user-images.githubusercontent.com/26079928/81656772-fc011000-943f-11ea-97a0-eb0200663c12.png)

As you can see, ViewBinding is totally different of ViewDataBinding. In your module where you created the viewBinding method you could make another one with viewDataBinding and I think it'll work, you just have to change the ViewBinding variable to ViewDataBinding  as I did for test in the following image : 
![image](https://user-images.githubusercontent.com/26079928/81657630-b133c800-9440-11ea-88d6-7dfb2c8d4200.png)

**Comment by mihaiAdascalitei** [comment]
Hey! It was my bad, I had to update some dependencies, now it works! 
Sorry for disturbing and confusing.
