### ISSUE TITLE
How make sticky headers?

### ISSUE THREAD

**Issue by ShurikuS57** [sockeqwe/AdapterDelegates#90]
How to do it like this?
![7qE9v](https://user-images.githubusercontent.com/1519692/85287981-b4898d00-b49d-11ea-966e-3f9626ecffa5.gif)

**Comment by tamimattafi** [comment]
Any updates on this?

**Comment by sockeqwe** [comment]
Hi, 
Sticky headers are not part of this library. This library is only about dealing with ViewHolders etc. more gracefully.

I'm sorry, but you have to look that up on your own or find a RecyclerView  (UI) libraryy´that supports sticky headers. I think it will also work in combination with AdapterDelegates.


Just to get some inspiration: you may found this useful
https://medium.com/swlh/android-recyclerview-stickyheader-without-external-library-25845ec3e20f

and I think you can use AdapterDelegates for the underlying dataset of your recyclerview
